name: Publish Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate release artifacts
        run: |
          mkdir release
          cp stacks/stacks.json release/stacks.json

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: release/stacks.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
